stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
    outs:
      - data/data.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/data.csv
    outs:
      - model/model.pkl
      - data/test.csv
      - data/test_labels.csv

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - model/model.pkl
      - data/test.csv
      - data/test_labels.csv
    metrics:
      - metrics.json
